/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ScanMem */

#ifndef _Included_ScanMem
#define _Included_ScanMem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ScanMem
 * Method:    s_get_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ScanMem_s_1get_1version
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
